cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('add/<item_id>/', views.add_to_cart, name='add_to_cart'),
    path("update/<item_id>/", views.update_cart, name="update_cart"),
    path('remove/<item_id>/', views.remove_from_cart, name='remove_from_cart'),
    # path('apply_coupon/', views.apply_coupon, name='apply_coupon'),
]

checkout/urls.py
from django.urls import path
from . import views
from .webhooks import webhook
from .views import apply_coupon

urlpatterns = [
    path('', views.checkout, name='checkout'),
    path('checkout_success/<order_id>', views.checkout_success,
         name='checkout_success'),
    path('cache_checkout_data/', views.cache_checkout_data,
         name='cache_checkout_data'),
    path('wh/', webhook, name='webhook'),
    path('apply_coupon/', apply_coupon, name='apply_coupon'),
]

genstar_music_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path("", include('store.urls')),
    path("products/", include('products.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('profiles/', include('profiles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings
from django.utils import timezone

from django_countries.fields import CountryField
from products.models import Product
from profiles.models import UserProfile


class Order(models.Model):
    '''Create an order model to store order details'''
    order_id = models.CharField(max_length=50, null=False, editable=False)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.SET_NULL,
                                     null=True, blank=True,
                                     related_name='orders')
    first_name = models.CharField(max_length=50, null=False, blank=False)
    last_name = models.CharField(max_length=50, null=False, blank=False)
    email_address = models.EmailField(max_length=250, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False,
                                       default='')
    building_number1 = models.CharField(max_length=80, null=False, blank=False,
                                        default='')
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    building_number2 = models.CharField(max_length=80, null=True, blank=True)
    postal_code = models.CharField(max_length=20, null=True, blank=True)
    city = models.CharField(max_length=50, null=False, blank=False)
    country = CountryField(blank_label='Country *', null=False, blank=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    delivery_cost = (models.DecimalField(max_digits=6, decimal_places=2,
                                         null=False, default=0))
    order_total = (models.DecimalField(max_digits=10, decimal_places=2,
                                       null=False, default=0))
    grand_total = (models.DecimalField(max_digits=10, decimal_places=2,
                                       null=False, default=0))
    tax = (models.DecimalField(max_digits=10, decimal_places=2,
                               null=False, default=0))
    coupon = (models.ForeignKey('Coupon', null=True, blank=True,
                                on_delete=models.SET_NULL))

    def _generate_order_id(self):
        '''Generate a random, unique order id using UUID'''
        return uuid.uuid4().hex.upper()

    def apply_coupon(self, coupon):
        '''Apply a gift coupon to the order'''
        self.discount = coupon.coupon_value
        self.coupon = coupon
        self.save()
        print(f'Coupon value {coupon.coupon_value}')
        print(f'Order total {self.order_total}')

    def update_total(self):
        """
        Update grand total each time a line item is added,
        accounting for delivery costs.
        """
        self.order_total = (self.line_items.aggregate(Sum('line_item_total'))
                            ['line_item_total__sum'] or 0)
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = settings.STANDARD_DELIVERY_COST
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

        class Meta:
            ordering = ('-created',)

        def __str__(self):
            return f'Order {self.id}'

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_id:
            self.order_id = self._generate_order_id()
        super().save(*args, **kwargs)

        def __str__(self):
            return self.order_id


class OrderLineItem(models.Model):
    '''Create an order line item model to store order line item details'''
    order = (models.ForeignKey(Order, null=False,
                               blank=False, on_delete=models.CASCADE,
                               related_name='line_items'))
    product = (models.ForeignKey(Product, null=False, blank=False,
                                 on_delete=models.CASCADE))
    quantity = models.IntegerField(null=False, blank=False, default=0)
    line_item_total = (models.DecimalField(max_digits=6, decimal_places=2,
                                           null=False, blank=False,
                                           editable=False))

    def save(self, *args, **kwargs):
        '''Override the original save method to set the line item total and
        update the order total'''
        self.line_item_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_id}'


class Coupon(models.Model):
    '''Create a gift coupon model to store gift coupon details'''
    coupon_id = models.CharField(max_length=50, null=False, editable=False)
    coupon_code = models.CharField(max_length=50, null=False, blank=False)
    coupon_value = (models.DecimalField(max_digits=6, decimal_places=2,
                                        null=False, blank=False))
    coupon_expiry = models.DateField(null=False, blank=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=False)
    description = models.CharField(max_length=250, null=False, blank=False)

    def _generate_coupon_id(self):
        '''Generate a random, unique coupon id using UUID'''
        return uuid.uuid4().hex.upper()

    def is_valid(self):
        '''Check if the coupon is valid'''
        return self.active and self.coupon_expiry >= timezone.now().date()

    def save(self, *args, **kwargs):
        '''Override the original save method to set the coupon id if it
        hasn't been set already'''

        if not self.coupon_id:
            self.coupon_id = self._generate_coupon_id()
        super().save(*args, **kwargs)

        if self.coupon_expiry < timezone.now().date():
            raise ValueError('Coupon has expired')

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Coupon {self.coupon_id}'

checkout/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.shortcuts import HttpResponse
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.conf import settings

import stripe
import json

from profiles.models import UserProfile
from profiles.forms import UserProfileForm

from cart.contexts import cart_contents
from products.models import Product
from .forms import OrderForm
from .models import Order, OrderLineItem, Coupon


@require_POST
def cache_checkout_data(request):
    ''' A view to cache checkout data'''
    try:
        pid = request.POST.get('client_secret').split('_secret')[0]
        stripe.api_key = settings.STRIPE_SECRET_KEY
        stripe.PaymentIntent.modify(pid, metadata={
            'cart': json.dumps(request.session.get('cart', {})),
            'save_info': request.POST.get('save_info'),
            'username': request.user,
            'order_id': request.POST.get('order_id'),
        })
        return HttpResponse(status=200)
    except Exception as e:
        messages.error(request, 'Sorry, your payment cannot be \
            processed right now. Please try again later.')
        return HttpResponse(content=e, status=400)


def checkout(request):
    ''' A view to return the checkout page'''

    stripe_public_key = settings.STRIPE_PUBLIC_KEY
    stripe_secret_key = settings.STRIPE_SECRET_KEY

    if request.method == 'POST':
        cart = request.session.get('cart', {})

        form_data = {
            'first_name': request.POST['first_name'],
            'last_name': request.POST['last_name'],
            'email_address': request.POST['email_address'],
            'phone_number': request.POST['phone_number'],
            'country': request.POST['country'],
            'postal_code': request.POST['postal_code'],
            'city': request.POST['city'],
            'street_address1': request.POST['street_address1'],
            'building_number1': request.POST['building_number1'],
            'street_address2': request.POST['street_address2'],
            'building_number2': request.POST['building_number2'],
        }
        order_form = OrderForm(form_data)
        if order_form.is_valid():
            order = order_form.save()
            for item_id, item_data in cart.items():
                try:
                    product = Product.objects.get(id=item_id)
                    order_line_item = OrderLineItem(
                        order=order,
                        product=product,
                        quantity=item_data,
                        )
                    order_line_item.save()
                except Product.DoesNotExist:
                    messages.error(request, (
                        "One of the products in your bag wasn't found in \
                            our database. "
                        "Please call us for assistance!")
                    )
                    order.delete()
                    return redirect(reverse('view_cart'))

            request.session['save_info'] = 'save-info' in request.POST
            return redirect(reverse('checkout_success', args=[order.order_id]))
        else:
            messages.error(request, 'There was an error with your form. \
                Please double check your information.')
    else:
        cart = request.session.get('cart', {})
        if not cart:
            messages.error(request, "There's nothing in your cart \
                at the moment")
            return redirect(reverse('products'))

        current_cart = cart_contents(request)
        total = current_cart['grand_total']
        stripe_total = round(total * 100)
        stripe.api_key = stripe_secret_key

        intent = stripe.PaymentIntent.create(
            amount=stripe_total,
            currency=settings.STRIPE_CURRENCY,
            metadata={
                'cart': json.dumps(request.session.get('cart', {})),
                'username': request.user,
                'save_info': 'save-info' in request.POST,
                'order_id': 'order.id',
            }
        )

        if request.user.is_authenticated:
            try:
                user_profile = UserProfile.objects.get(user=request.user)
                order_form = OrderForm(initial={
                    'first_name': user_profile.default_first_name,
                    'last_name': user_profile.default_last_name,
                    'email_address': user_profile.default_email_address,
                    'phone_number': user_profile.default_phone_number,
                    'country': user_profile.default_country,
                    'postal_code': user_profile.default_postal_code,
                    'city': user_profile.default_city,
                    'street_address1': user_profile.default_street_address1,
                    'building_number1': user_profile.default_building_number1,
                    'street_address2': user_profile.default_street_address2,
                    'building_number2': user_profile.default_building_number2,
                })
            except UserProfile.DoesNotExist:
                order_form = OrderForm()
        else:
            order_form = OrderForm()

        order_form = OrderForm()

    if not stripe_public_key:
        messages.warning(request, 'Stripe public key is missing. \
            Did you forget to set it in your environment?')

    template = 'checkout/checkout.html'
    context = {
        'order_form': order_form,
        'stripe_public_key': stripe_public_key,
        'client_secret': intent.client_secret,
    }

    return render(request, template, context)


def checkout_success(request, order_id):
    ''' A view to return the checkout success page'''

    save_info = request.session.get('save_info')
    order = get_object_or_404(Order, order_id=order_id)

    if request.user.is_authenticated:
        profile = UserProfile.objects.get(user=request.user)
        # Attach the user's profile to the order
        order.user_profile = profile
        order.save()

        # Save the user's info
        if save_info:
            profile_data = {
                'default_first_name': order.first_name,
                'default_last_name': order.last_name,
                'default_email_address': order.email_address,
                'default_phone_number': order.phone_number,
                'default_street_address1': order.street_address1,
                'default_building_number1': order.building_number1,
                'default_street_address2': order.street_address2,
                'default_building_number2': order.building_number2,
                'default_city': order.city,
                'default_postal_code': order.postal_code,
                'default_country': order.country,
            }
            user_profile_form = UserProfileForm(profile_data, instance=profile)
            if user_profile_form.is_valid():
                user_profile_form.save()

    tax_rate = settings.TAX_RATE
    tax = order.order_total * tax_rate / 100

    order.tax = tax
    order.save()

    messages.success(request, f'Order successfully processed! \
                Your order number is {order.order_id}. \
                A confirmation email will be sent to {order.email_address}.')

    if 'cart' in request.session:
        update_product_quantities(request)
        del request.session['cart']

    template = 'checkout/checkout_success.html'
    context = {
        'order': order,
        'save_info': save_info,
    }

    return render(request, template, context)


def update_product_quantities(request):
    ''' A view to update product quantities after a successful checkout'''

    cart = request.session.get('cart', {})
    for item_id, item_data in cart.items():
        try:
            product = Product.objects.get(id=item_id)
            product.quantity_in_stock -= item_data
            product.save()
        except Product.DoesNotExist:
            messages.error(request, (
                "One of the products in your bag wasn't found \
                    in our database. "
                "Please call us for assistance!")
            )
            return redirect(reverse('view_cart'))


def apply_coupon(request):
    ''' A view to apply a coupon to the order'''
    if request.method == 'POST':
        coupon_code = request.POST.get('coupon_code')
        if coupon_code:
            try:
                coupon = (Coupon.objects.get(coupon_code=coupon_code,
                                             active=True))
                # Implement this function to get or create the order
                order = get_or_create_order(request)
                # Implement a method in your Order model to apply the coupon
                order.apply_coupon(coupon)
                messages.success(request, f"Coupon '{coupon.coupon_code}'\
                                applied successfully! \
                                Coupon value is {coupon.coupon_value} eur.")
            except Coupon.DoesNotExist:
                messages.error(request, "Invalid coupon code.")

    return redirect(reverse('checkout'))


def get_or_create_order(request):
    ''' A view to get or create an order'''
    order_id = request.session.get('order_id')
    if order_id:
        order = Order.objects.get(id=order_id)
    else:
        order = Order.objects.create()
        request.session['order_id'] = order.id
    return order

checkout/templates/checkout/checkout_success.html
{% extends "base.html" %}
{% load static %}
{% load custom_filters %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'checkout/css/checkout.css' %}">
{% endblock %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col">
                <hr>
                <h2 class="logo-font mb-4">Thank you for your order!</h2>
                <hr>
                <p class="text-black">Your order information is below. A confirmation email was sent to <strong>{{ order.email_address }}</strong>.</p>
            </div>
        </div>
<!-- Order info -->
        <div class="row">
            <div class="col-12 col-lg-7">
                <div class="order-confirmation-wrapper p-2 border">
                    <div class="row">
                        <div class="col">
                            <h6 class="text-muted">Order Info:</h6>
                            <hr>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12 col-md-4">
                            <p class="mb-0 mt-0 text-black font-weight-bold">Order Number:</p>
                        </div>
                        <div class="col-12 col-md-8 text-md-right">
                            <p class="mb-0" id="id_order_id">{{ order.order_id }}</p>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12 col-md-4">
                            <p class="mb-0 mt-0 text-black font-weight-bold">Order Date:</p>
                        </div>
                        <div class="col-12 col-md-8 text-md-right">
                            <p class="mb-0">{{ order.created }}</p>
                        </div>
                    </div>
                    <hr>
<!-- Order Details -->
                    <div class="row">
                        <div class="col">
                            <h6 class="text-muted">Order Details:</h6>
                            <hr>
                        </div>
                    </div>
                    <p>Number of Items in your order - {{ order.line_items.count }}</p>
                    {% for item in order.line_items.all %}
                    <div class="row gy-3 mb-4">
                        <div class="col-lg-6">
                            <div class="me-lg-6">
                                <div class="d-flex">
                                    <img src="{{ item.product.image.url }}" alt="{{ item.product.name }}" class="border rounded me-3"
                                        style="width: 96px; height: 96px;">
                                    <div class="">
                                        <a class="nav-link" href="{% url 'product_detail' product_id=item.product.id %}" style="text-decoration: none;">
                                            {{ item.product.name }}
                                        </a>
                                        <p>
                                            <a class="text-muted small" href="{% url 'products_in_category' category_id=item.product.category.id %}" style="text-decoration: none;">
                                                <i class="fas fa-tag mr-1"></i> {{ item.product.category.friendly_name }}
                                            </a>
                                        </p>
                                        <p>
                                            <small class="text-muted text-nowrap"> Ref.nr: {{ item.product.sku }} </small>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-sm-6 col-6 d-flex flex-row flex-lg-column flex-xl-row text-nowrap">                                         
                            <div class="mx-5">
                                Item Quantity: {{ item.quantity }}
                            </div>
                        </div>
                        <div class="col-lg-2 col-sm-6 col-6 d-flex flex-row flex-lg-column flex-xl-row text-nowrap">                                         
                            <div class="mx-5">
                                <h6 class="total-price" data-row-id="{{ item.product.id }}">{{ item.product.price|multiply:item.quantity }} <i class="fa-solid fa-euro-sign fa-sm"></i></h6>
                                <small class="text-muted text-nowrap"> {{ item.product.price }} <i class="fa-solid fa-euro-sign fa-sm"></i> / per item </small>
                            </div>
                        </div>
                    </div>
                    {% endfor %}

                    {% for item in order.cart_items.all %}
                    <p>{{ item.product.name }}</p>
                    {% endfor %}
                    <hr>
                    <div class="row">
                        <div class="col">
                            <h6 class="text-muted">Delivery Address:</h6>
                            <hr>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12 col-md-4">
                            <p class="mb-0 mt-0 text-black font-weight-bold">Full Name:</p>
                        </div>
                        <div class="col-12 col-md-8 text-md-right">
                            <p class="mb-0">{{ order.first_name }}</p>
                            <p class="mb-0">{{ order.last_name }}</p>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12 col-md-4">
                            <p class="mb-0 mt-0 text-black font-weight-bold">Address 1:</p>
                        </div>
                        <div class="col-12 col-md-8 text-md-right">
                            <p class="mb-0">{{ order.street_address1 }}</p>
                            <p class="mb-0">{{ order.building_number1 }}</p>
                        </div>
                    </div>

                    {% if order.street_address2 %}
                    <div class="row">
                        <div class="col-12 col-md-4">
                            <p class="mb-0 mt-0 text-black font-weight-bold">Address 2:</p>
                        </div>
                        <div class="col-12 col-md-8 text-md-right">
                            <p class="mb-0">{{ order.street_address2 }}</p>
                            <p class="mb-0">{{ order.building_number2 }}</p>
                        </div>
                    </div>
                    {% endif %}

                    <div class="row">
                        <div class="col-12 col-md-4">
                            <p class="mb-0 mt-0 text-black font-weight-bold">City:</p>
                        </div>
                        <div class="col-12 col-md-8 text-md-right">
                            <p class="mb-0">{{ order.city }}</p>
                        </div>
                    </div>

                    {% if order.postal_code %}
                    <div class="row">
                        <div class="col-12 col-md-4">
                            <p class="mb-0 mt-0 text-black font-weight-bold">Postal Code:</p>
                        </div>
                        <div class="col-12 col-md-8 text-md-right">
                            <p class="mb-0">{{ order.postal_code }}</p>
                        </div>
                    </div>
                    {% endif %}

                    <div class="row">
                        <div class="col-12 col-md-4">
                            <p class="mb-0 mt-0 text-black font-weight-bold">Country:</p>
                        </div>
                        <div class="col-12 col-md-8 text-md-right">
                            <p class="mb-0">{{ order.country }}</p>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12 col-md-4">
                            <p class="mb-0 mt-0 text-black font-weight-bold">Phone Number:</p>
                        </div>
                        <div class="col-12 col-md-8 text-md-right">
                            <p class="mb-0">{{ order.phone_number }}</p>
                        </div>
                    </div>
        <!-- Payment Info -->
                    <hr>
                    <div class="row">
                        <div class="col">
                            <h6 class="text-muted">Billing Info:</h6>
                            <hr>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 col-md-4">
                            <p class="mb-0 mt-0 text-black font-weight-bold">Order Total:</p>
                        </div>
                        <div class="col-12 col-md-8 text-md-right">
                            <p class="mb-0">{{ order.order_total }} <i class="fa-solid fa-euro-sign fa-sm"></i></p>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12 col-md-4">
                            <p class="mb-0 mt-0 text-black font-weight-bold">Taxes (25%):</p>
                        </div>
                        <div class="col-12 col-md-8 text-md-right">
                            <p class="mb-0">{{ order.tax|floatformat:2 }} <i class="fa-solid fa-euro-sign fa-sm"></i></p>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12 col-md-4">
                            <p class="mb-0 mt-0 text-black font-weight-bold">Delivery Charges:</p>
                        </div>
                        <div class="col-12 col-md-8 text-md-right">
                            <p class="mb-0">{{ order.delivery_cost }} <i class="fa-solid fa-euro-sign fa-sm"></i></p>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12 col-md-4">
                            <p class="mb-0 mt-0 text-black font-weight-bold">Grand Total:</p>
                        </div>
                        <div class="col-12 col-md-8 text-md-right">
                            <p class="mb-0">{{ order.grand_total }} <i class="fa-solid fa-euro-sign fa-sm"></i></p>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div class="row">
			<div class="col-12 col-lg-7 text-right">
                {% if from_profile %}
                    <a href="{% url 'view_profile' %}" class="btn btn-black rounded-0 my-2">
                        <span class="icon mr-2">
                            <i class="fas fa-angle-left"></i>
                        </span>
                        <span class="text-uppercase">Back to Profile</span>
                    </a>
                {% else %}
                    <a href="{% url 'products' %}" class="btn btn-black rounded-0 my-2">
                        <span class="icon mr-2">
                            <i class="fas fa-gifts"></i>
                        </span>
                        <span class="text-uppercase">Now check out the latest deals!</span>
                    </a>
                {% endif %}
			</div>
		</div>
    </div>
{% endblock %}